export interface IProduct {
    applydevolution: string,
    brandproviderid: number,
    characteristics: string,
    conditions: string,
    featured: number,
    high: number,
    id: number,
    linkvideo: string,
    long: number,
    optionscreatedat: string,
    optionsstatus: string,
    optionsupdatedat: string,
    product: string,
    sku: string,
    subcategoryid: number,
    volume: number,
    warrantyid: number,
    weight: number,
    wide: number,

}