// Generated by https://quicktype.io
export interface ThingsResponse {
  status:       string;
  totalResults: number;
  products:     Product[];
}

export interface Product {
  source:       Source;
  title:        string;
  description?: string;
  url:          string;
  urlToImage?:  string;
  tallas:       string;
  color?:       string;
}

export interface Source {
  id?:  string;
  name: string;
}


export interface ProductsByCategoryAndPage {
  [key: string] : {
      page: number,
      products: Product[]
  }
}
